### ISSUE TITLE
Nominate

### ISSUE THREAD

**Issue by michaelbragg** [reachplc/2014.birminghamsportsawards.co.uk#5]
## Todo:
- [x] Nominations API
- [x] HTML Form
- [x] Confirmation Email Template
- [x] Nomination Email Template

**Notes**: 
- Need a confirmation email to be sent to the applicant once they have registered confirming that we have received them. 
- Nomination email to be received by contact at Trinity Mirror and Champions UK.

**Comment by michaelbragg** [comment]
# Content

## Intro

> To nominate your athlete, team or volunteer into this year’s awards, simply fill in their details below and state which award you wish to put them forward for, demonstrating in a maximum of 250 words why you think they should be a winner at the 2014 Birmingham Sports Awards. 
> If you are shortlisted as a finalist you shall be contacted during the week commencing August 8th. As a finalist you will receive 2 tickets to the awards ceremony on Thursday, September 18, 2014, at Aston Villa Football Club, Birmingham.
> All entries are to be judged by an independent judging panel compiled by Trinity Mirror. 

## Nomination Form

> Name of Nominee:
> Nominees email address:
> Nominees Phone Number:
> Category: (we will need a drop down list of all 13 categories on here)
> I would like to nominate the nominee for this award because: (this box will need to allow for a large amount of text)
> Nominated by:
> You’re Phone Number:
> 
> Once you have completed the nomination form, you will be sent a welcome email.
> All information provided by applicants to the Birmingham Sports Awards 2014 will be regarded as confidential and shared only between the publication (trinity Mirror), the organiser (Champions (UK) plc) and the judging panel.  
> All data will be securely stored and, following completion of the Birmingham Sports Awards 2014, all applications and associated information will be deleted by the Trinity Mirror and Champions (UK) plc. Contact information will be retained by the organisers for marketing purposes.
> Information will not be passed to third parties.

**Comment by michaelbragg** [comment]
- [x] Add a Nominator Email input field so we can send them the 'welcome email'

**Comment by michaelbragg** [comment]
- [x] Client side form validation
